- name: Scan for vg_data volume group
  command: vgdisplay vg_data
  register: test_vg_data
  ignore_errors: yes

- name: Create a physical volume on {{ data_block_dev_path }}
  command: /usr/sbin/pvcreate {{ data_block_dev_path }}
  when: test_vg_data.rc==5

- name: Create volume group on ephemeral
  lvg: vg=vg_data pvs={{ data_block_dev_path }}
  when: test_vg_data.rc==5

- name: Check for swap
  shell: 'swapon -s | grep -E "^/"'
  register: swap_configured
  ignore_errors: yes

- name: Scan for swap
  command: lvdisplay vg_data/swap
  register: test_lv_swap
  ignore_errors: yes

- name: Create logical volume for swap
  lvol: lv=swap vg=vg_data size={{ ansible_memtotal_mb * 2 }}M
  when: test_lv_swap.rc==5

- name: Run mkswap on swap lv
  command: mkswap /dev/mapper/vg_data-swap
  when: swap_configured|failed

- command: 'swapon /dev/mapper/vg_data-swap'
  when: swap_configured|failed

- name: Write swap entry in fstab
  mount:
    name: none
    src: /dev/mapper/vg_data-swap
    fstype: swap
    state: present

- name: Create logical volume for docker
  lvol:
    lv=docker vg=vg_data opts="-T" size="100%FREE"
