- name: Add ambari repository
  get_url:
    url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.2.0.0/ambari.repo
    dest: /etc/yum.repos.d/ambari.repo

- name: install ambari-server and openjdk
  yum: name={{ item }}
  with_items:
    - ambari-server
    - java-1.8.0-openjdk

- name: run ambari setup
  shell: ambari-server setup -j /etc/alternatives/jre -s

- name: start ambari service
  service: name=ambari-server state=running enabled=yes
