- name: download latest miniconda
  get_url:
    url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /tmp/miniconda.sh

- name: install miniconda to /opt/conda
  shell: /bin/bash /tmp/miniconda.sh -f -b -p /opt/conda
  args:
    creates: /opt/conda
