---

# http://developerblog.redhat.com/2015/11/19/dns-your-openshift-v3-cluster/
- name: install dnsmasq
  yum: name=dnsmasq state=present

- name: enable and run dnsmasq service
  service:
    name: dnsmasq
    enabled: yes
    state: started

- name: open ports 53 for DNS
  lineinfile:
    line: "-A INPUT -p udp -m udp --dport 53 -j ACCEPT"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT'

- name: install java 1.8 jdk
  yum: name=java-1.8.0-openjdk-devel state=present

- name: install tomcat
  yum: name=tomcat state=present

- name: install tomcat webapps
  yum: name=tomcat-webapps state=present

- name: configure tomcat server
  copy: src=roles/cluster_master/files/server.xml dest=/etc/tomcat/server.xml
  notify: restart tomcat

- name: install maven
  yum: name=maven state=present

- name: download and extract the rest api code for checking yarn resource status
  unarchive: src="https://github.com/apurva3000/yarn-status/archive/beta.tar.gz" dest=/tmp copy=no

- name: compile the yarn resource status rest api code using maven
  command: chdir=/tmp/yarn-status-beta /usr/bin/mvn compile war:war

- name: move the generated war to tomacat webapps directory
  command: mv /tmp/yarn-status-beta/target/ResourceStatus-beta.war /var/lib/tomcat/webapps/ResourceStatus-beta.war

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes
